### ISSUE TITLE
findAllListingActive not grabbing the keywords parameter

### ISSUE THREAD

**Issue by Yakito** [inakiabt/etsy-php#18]
Hi, I am not sure if I am doing something wrong, but when I run findAllListingActive like this:
$api->findAllListingActive(array('params' => array('offset' => '50', 'page' => '2', 'keywords' => 'shirt')))

All parameters are working except for keywords which return empty in the params array at the end of the response.

The method (https://www.etsy.com/developers/documentation/reference/listing#method_findalllistingactive) takes a keyword parameter as text.

Any idea what might be wrong? 

Thanks a lot!

**Comment by inakiabt** [comment]
Seems like it is an Etsy's bug. I debugged your example and all the `params` are being sent as Etsy's documentation says.
If you find any other info, please update this issue.
Thanks.
