### ISSUE TITLE
Image is not uploading.

### ISSUE THREAD

**Issue by ziaadilh** [inakiabt/etsy-php#22]
I tried to use as you provided in example like:
`$method = 'uploadListingImage';
		$args = array(
			'params' => array(
				'listing_id' => 123456
			),
			'data' => array(
				'image' => array('file.jpg;type=image/jpeg')
			)
		);`

I used like:

`$taxo = $api->uploadListingImage(
        array(
            'params' => array(
                'listing_id' => 509505496,
            ),
            'data' => array(
                'image'=> array('15.1.jpg;type=image/jpeg')
            )
        )
    );`

I got the error message:
 'Exception' with message 'Invalid params for method "uploadListingImage": Invalid data param type "image" (15.1.jpg;type=image/jpeg: string): required type "imagefile"

Note: my image path is the same of the script. 

Thanks.

**Comment by inakiabt** [comment]
You forgot the `@`. Take a look to this example: https://github.com/inakiabt/etsy-php/blob/b38b81854af4b2fbbd70f0e7bb983852b27a105b/README.md#examples
