### ISSUE TITLE
Adding attribute to an item.

### ISSUE THREAD

**Issue by ziaadilh** [inakiabt/etsy-php#25]
I am not sure if it's support attributes to an item. I looked into documentation as well as into the code base there is no such info. Can you help us to explain? Thanks.

**Comment by inakiabt** [comment]
This library it's just a wrapper of etsy's API. It adds parameters validation and a simple way to make request to the API. Just that. It uses Etsy's API schema (methods.json) to do that, so what this library can do it's what theirs API do.

The idea behind this wrapper is map PHP code to that schema, so I'm not sure all the kind of requests and params this library supports, but I can assure that if I keep an eye on Etsy's API about required params and params types this library will do the job (that definition is on the methods.json file).

I'd agree that it is not perfect and could be issues and features unsupported, but as for now it's been doing ok.

That being said, I'd recommend to take a look to Etsy's API documentation.
Thanks!

**Comment by ziaadilh** [comment]
Thanks that's right. I am also trying to help others. There is no API  support for that. I explore their documentation.
