### ISSUE TITLE
Error while OAuth process

### ISSUE THREAD

**Issue by niklasgrau** [inakiabt/etsy-php#42]
Hello there,

we are currently getting the following error while authentication process:
`Error: Invalid auth/bad request (got a 411, expected HTTP/1.1 20X or a redirect): Array ( ) 411 - Length Required`.

We reported this issue to etsy and it seems that they changed something. We got the following information:

> Due to recent updates, you will now have to specify the GET method when using Oauth. Here’s an example:
> `$req_token = $oauth->getRequestToken(“https://openapi.etsy.com/v2/oauth/request_token?scope=email_r%20listings_r“, ‘oob’, “GET”);`
> 
> `$acc_token = $oauth->getAccessToken(“https://openapi.etsy.com/v2/oauth/access_token”, null, $verifier, “GET”);`
> 

Would it be possible to add the `GET` parameter to these two functions? I think everyone should run into this issue at the moment.

**Comment by mborn319** [comment]
I had this issue on my machine as well.
This is easily resolved by adding the `GET` method type to the `getAccessToken()` and `getRequestToken()` function calls, as mentioned above.

https://github.com/inakiabt/etsy-php/blob/master/src/Etsy/EtsyClient.php#L85
https://github.com/inakiabt/etsy-php/blob/master/src/Etsy/EtsyClient.php#L96

@inakiabt Mind if I submit this as a PR?
