### ISSUE TITLE
Composer is not pulling the latest version?

### ISSUE THREAD

**Issue by ipsod** [inakiabt/etsy-php#8]
I'm using to use composer to grab this, but it's not pulling the recent merges.  I tried deleting the folder and having composer re-grab it, but it's still getting the old version.

I don't know if this is an issue with the code base.  I don't really understand what's happening.

**Comment by inakiabt** [comment]
Can you post your composer.json dependencies part?

--
Iñaki Abete

**Comment by ipsod** [comment]
```
	"require": {
        "inakiabt/etsy-php":"dev-master"
	},
```

**Comment by inakiabt** [comment]
Seems like there was a change in Packagist. Now, if you want to have your packagist libraries auto-updated, you have to setup a hook on Github to send every change to Packagist.
I added the hook and now you'll be able to get the latest version!
Thanks again.
